spring.application.name=Smart_Menu_Back
server.port=9002

spring.mongodb.uri=mongodb://127.0.0.1:27017/smart_menu

jwt.secret=0KiFbxtgqASu8Acyu6yA+HmilwrcRx4BpRagtnpk6PM=
jwt.expiration-ms=3600000

app.frontend.url=http://localhost:4200